### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by jbungo**

### CODE REVIEW

**Comment by jbungo** [comment]
Add 'Jet'

**Comment by sloretz** [comment]
Cool robot! It looks like these images are for the post in #95. Would you mind adding these images to #95 instead?

**Comment by jbungo** [comment]
Thanks, but how?

Joe Bungo
Deep Learning Institute Program Manager
NVIDIA Corporation
developer.nvidia.com/teaching-kits<https://developer.nvidia.com/teaching-kits>
Mobile: +1 (512) 293-7324
jbungo@nvidia.com<mailto:jbungo@nvidia.com>

**Comment by tfoote** [comment]
You can check out the branch and add commits to it. 

In your case you can merge patch-2 onto patch-1 on your repo. And then the contents will all be in the same branch submitted in #95 

You can do that through the web UI here: https://github.com/jbungo/robots.ros.org/compare/patch-1...jbungo:patch-2

Closing this as the changes should come in from #95

**Comment by jbungo** [comment]
Okay – I think I have done this. What now?

Joe Bungo
Deep Learning Institute Program Manager
NVIDIA Corporation
developer.nvidia.com/teaching-kits<https://developer.nvidia.com/teaching-kits>
Mobile: +1 (512) 293-7324
jbungo@nvidia.com<mailto:jbungo@nvidia.com>

**Comment by tfoote** [comment]
You need to merge the pull request you opened: https://github.com/jbungo/robots.ros.org/pull/1 so that patch-2 changes are on top of patch-1 changes and will appear for us to review in #95

**Comment by jbungo** [comment]
I think I did this now – can you confirm?

Joe Bungo
Deep Learning Institute Program Manager
NVIDIA Corporation
developer.nvidia.com/teaching-kits<https://developer.nvidia.com/teaching-kits>
Mobile: +1 (512) 293-7324
jbungo@nvidia.com<mailto:jbungo@nvidia.com>

**Pull request closed without merging**
