### PR TITLE
Bulldog

### PR DESCRIPTION
**Pull request by wzy0426**
I have removed add_robot.py~ and 2017-07-21-bulldog.md~.And the "&nbsp;" is no problem.I have tested it locally.

### CODE REVIEW

**Comment by wzy0426** [comment]
I don't konw much about this.If there have any other problem.I will correct it again.Thank you very much.

**Comment by wzy0426** [comment]
the "&--n-b-s-p;"  is no problem I have tested it locally.

**Comment by wzy0426** [comment]
"wiki.ros.org/Bulldog"this page we will create it as soon as pssible.

**Comment by wzy0426** [comment]
Wiki page of "wiki.ros.org/Bulldog",we will create it as soon as pssible

**Comment by wzy0426** [comment]
OK，I will  create it as soon as possible.Thank you.

**Comment by wzy0426** [comment]
The wiki page of Robots/Bulldog  have created.Any other problem?

**Comment by tfoote** [comment]
It's up and available now. http://robots.ros.org/bulldog/

Some feedback for you. I'd recommend a few more pictures or videos.

And the Website link looks to be invalid as mentioned above. I'd recommend an update to fix that.

**Comment by wzy0426** [comment]
Thanks for your recommend. I  will  have a  try.

**Pull request merged**
