### PR TITLE
Add Tinymovr motor controller

### PR DESCRIPTION
**Pull request by yconst**

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
Thanks for the addition. It looks good to me in the preview.

**Comment by tfoote** [comment]
Sorry CI is failing with the new python version, can you please rebase on top of #284 ?

**Comment by yconst** [comment]
I updated the branch

**Comment by yconst** [comment]
Is there some update on this?

**Review by tfoote — APPROVED** [review]
I'm not sure why CI didn't automatically rerun. So I just checked it manually by hand.

**Pull request merged**
