### PR TITLE
Add RoboCar1/10X

### PR DESCRIPTION
**Pull request by z-andrei-pak**
Hi,
We want to add a new robot description.
The contribution guidelines were read, but it's our first PR to this repo, so something can be missing.
Please, review the change.

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Please take a moment to add a wiki page which points the developers to the developer documentation. It may mostly point to the Readme on GitHub but we'd like to have a centralized place to look for documentation. https://github.com/ros-infrastructure/robots.ros.org/blame/gh-pages/contributing.md#L29

**Comment by z-andrei-pak** [comment]
Thank you. After my request of being added to ros wiki is completed, I'll create a short page on the wiki.

**Comment by z-andrei-pak** [comment]
Done. Please, check if it's ok.
http://wiki.ros.org/Robots/RoboCar110X

**Review by tfoote — APPROVED** [review]
Thanks for filling it in.

**Pull request merged**
