### PR TITLE
Update site layouts

### PR DESCRIPTION
**Pull request by tfoote**
Still in progress. Putting this PR up for visibility. 

This started out as re implementing #28 and grew from there. 

The main thing that this does is move the image and info box into the header. It's a flexbox that scales nicely. And it wraps for small screens. There's one issue that the threshold for the content doesn't change when it wraps so the image is surpressed.

I also put some time into the answers.ros.org feed layout.

And removed some of the colorful link decorators.

I started looking at the contributing guide, but there will be more work on that front.

### CODE REVIEW

**Comment by wjwwood** [comment]
@tfoote do you want a review on this now? Or should I wait until later?

**Comment by tfoote** [comment]
I've got a few more changes, I will try to get in tonight before it's ready for review.

**Comment by tfoote** [comment]
@wjwwood this is ready for review

**Comment by tfoote** [comment]
Thanks @wjwwood fixed a few things and opened issues for the others.

**Pull request merged**
