### PR TITLE
Updated Volta Robot Banner to Video

### PR DESCRIPTION
**Pull request by nikhil-botsync**

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
This looks good, but can you remove the css change from the diff?

**Review by tfoote — APPROVED** [review]
Thanks for the quick fixup.

**Comment by tfoote** [comment]
I just checked and it looks like you have embedding disabled on that video. You'll want to enable it to support this use case. 

Screenshot from 2021-01-29 15-23-25

**Comment by nikhil-botsync** [comment]
Thanks for the heads up on the embed link @tfoote!  We fixed the broken link. Should be fine now.

**Pull request merged**
