### PR TITLE
added the TurtleBot3

### PR DESCRIPTION
**Pull request by robotpilot**
- added the TurtleBot3 on TurtleBot series
- changed TurtleBot's image to TurtleBot3

### CODE REVIEW

**Comment by tfoote** [comment]
This looks good as a result. However we should add TB3 not replace TB2 with TB3.

**Comment by robotpilot** [comment]
I understand that robots should be described in the same series, as shown below.

- Do not spam the site with small variants of robot names. Only have one entry per major version; a model upgrade should not generate a new page.

Can I ask you to fix it?

**Comment by tfoote** [comment]
Sure, TurtleBot2 vs TurtleBot3 are completely different robots. Different size etc. Whereas TurtleBot2 versus TurtleBot2e are small variants of the same robot. This directive is to say you shouldn't have TurtleBot3 Waffle, TurtleBot3 Burger, TurtleBot3 Car, TurtleBot3 Turtle etc.

**Comment by tfoote** [comment]
I touched it up, squashed and pushed it here: https://github.com/ros-infrastructure/robots.ros.org/commit/ca2491eaa29ec97c6acc5476114533c44a478047

**Pull request closed without merging**
